const assert = require('node:assert/strict');
const { calculate, WEEKS_PER_YEAR } = require('./calculation.js');
const input = { fullTimePay: 32000, contracted: 37.5, wholeTime: 37.5, sacrifice: 200, sacrificePeriod: 'monthly', minimumRate: 12.71 };
const full = calculate(input);
assert.equal(full.actualPay, 32000);
assert.equal(full.annualSacrifice, 2400);
assert.equal(full.below, false);
const part = calculate({ ...input, contracted: 18.75 });
assert.equal(part.actualPay, 16000);
assert.equal(part.adjustedPay, 13600);
assert.ok(part.hourlyAfter < full.hourlyAfter, 'Actual sacrifice must not be pro-rated again.');
assert.deepEqual(calculate({ ...input, sacrifice: 2400, sacrificePeriod: 'annual' }), full);
assert.equal(calculate({ ...input, contracted: 5, wholeTime: 10, unit: 'sessions', sessionHours: 3.75 }).hourlyAfter, part.hourlyAfter);
const annualHours = input.contracted * WEEKS_PER_YEAR;
const boundaryPay = input.minimumRate * annualHours;
assert.equal(calculate({ ...input, fullTimePay: boundaryPay, sacrifice: 0 }).below, false);
assert.equal(calculate({ ...input, fullTimePay: boundaryPay - 0.01, sacrifice: 0 }).below, true);
assert.throws(() => calculate({ ...input, contracted: 0 }));
assert.throws(() => calculate({ ...input, contracted: 40 }));
assert.throws(() => calculate({ ...input, sacrifice: -1 }));
assert.throws(() => calculate({ ...input, sacrifice: 4000 }));
assert.throws(() => calculate({ ...input, unit: 'sessions', sessionHours: NaN }));
assert.ok(calculate({ ...input, sacrifice: full.maxMonthlySacrifice }).below === false);
assert.ok(calculate({ ...input, sacrifice: full.maxMonthlySacrifice + 0.01 }).below === true);
console.log('Calculation checks passed: full-time, part-time, monthly/annual, sessions, threshold and invalid inputs.');
